image din Standard Cligne = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_01_Cligne.png", "True", "din_low.png")
image side din Standard Cligne = "din/side_Standard_01_Cligne.png"
image din Standard Cligne Rougit = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_02_Cligne_Rougit.png", "True", "din_low.png")
image side din Standard Cligne Rougit = "din/side_Standard_02_Cligne_Rougit.png"
image din Standard Colere = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_03_Colere.png", "True", "din_low.png")
image side din Standard Colere = "din/side_Standard_03_Colere.png"
image din Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_04_Colere_Rougit.png", "True", "din_low.png")
image side din Standard Colere Rougit = "din/side_Standard_04_Colere_Rougit.png"
image din Standard Degoute = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_05_Degoute.png", "True", "din_low.png")
image side din Standard Degoute = "din/side_Standard_05_Degoute.png"
image din Standard Sourire = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_06_Sourire.png", "True", "din_low.png")
image side din Standard Sourire = "din/side_Standard_06_Sourire.png"
image din Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_07_Sourire_Rougit.png", "True", "din_low.png")
image side din Standard Sourire Rougit = "din/side_Standard_07_Sourire_Rougit.png"
image din Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_08_Sourire_Yeuxfermes.png", "True", "din_low.png")
image side din Standard Sourire Yeuxfermes = "din/side_Standard_08_Sourire_Yeuxfermes.png"
image din Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "din_low.png")
image side din Standard Sourire Yeuxfermes Rougit = "din/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image din Standard Triste = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_10_Triste.png", "True", "din_low.png")
image side din Standard Triste = "din/side_Standard_10_Triste.png"
image din Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "din/main_Standard_11_Yeuxfermes_Rougit.png", "True", "din_low.png")
image side din Standard Yeuxfermes Rougit = "din/side_Standard_11_Yeuxfermes_Rougit.png"
