image Chuenpodo BrasCroises Badboy = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_01_Badboy.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Badboy = "Chuenpodo/side_BrasCroises_01_Badboy.png"
image Chuenpodo BrasCroises Badboy = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_01_Badboy.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Badboy = "Chuenpodo/side_BrasCroises_01_Badboy.png"
image Chuenpodo BrasCroises Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_02_Badboy_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Badboy Rougit = "Chuenpodo/side_BrasCroises_02_Badboy_Rougit.png"
image Chuenpodo BrasCroises Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_02_Badboy_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Badboy Rougit = "Chuenpodo/side_BrasCroises_02_Badboy_Rougit.png"
image Chuenpodo BrasCroises Colere = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_03_Colere.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Colere = "Chuenpodo/side_BrasCroises_03_Colere.png"
image Chuenpodo BrasCroises Colere = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_03_Colere.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Colere = "Chuenpodo/side_BrasCroises_03_Colere.png"
image Chuenpodo BrasCroises Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_04_Colere_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Colere Rougit = "Chuenpodo/side_BrasCroises_04_Colere_Rougit.png"
image Chuenpodo BrasCroises Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_04_Colere_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Colere Rougit = "Chuenpodo/side_BrasCroises_04_Colere_Rougit.png"
image Chuenpodo BrasCroises Degoute = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_05_Degoute.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Degoute = "Chuenpodo/side_BrasCroises_05_Degoute.png"
image Chuenpodo BrasCroises Degoute = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_05_Degoute.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Degoute = "Chuenpodo/side_BrasCroises_05_Degoute.png"
image Chuenpodo BrasCroises Sourire = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_06_Sourire.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire = "Chuenpodo/side_BrasCroises_06_Sourire.png"
image Chuenpodo BrasCroises Sourire = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_06_Sourire.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire = "Chuenpodo/side_BrasCroises_06_Sourire.png"
image Chuenpodo BrasCroises Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_07_Sourire_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire Rougit = "Chuenpodo/side_BrasCroises_07_Sourire_Rougit.png"
image Chuenpodo BrasCroises Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_07_Sourire_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire Rougit = "Chuenpodo/side_BrasCroises_07_Sourire_Rougit.png"
image Chuenpodo BrasCroises Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_08_Sourire_Yeuxfermes.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire Yeuxfermes = "Chuenpodo/side_BrasCroises_08_Sourire_Yeuxfermes.png"
image Chuenpodo BrasCroises Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_08_Sourire_Yeuxfermes.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire Yeuxfermes = "Chuenpodo/side_BrasCroises_08_Sourire_Yeuxfermes.png"
image Chuenpodo BrasCroises Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire Yeuxfermes Rougit = "Chuenpodo/side_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png"
image Chuenpodo BrasCroises Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Sourire Yeuxfermes Rougit = "Chuenpodo/side_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png"
image Chuenpodo BrasCroises Triste = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_10_Triste.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Triste = "Chuenpodo/side_BrasCroises_10_Triste.png"
image Chuenpodo BrasCroises Triste = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_10_Triste.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Triste = "Chuenpodo/side_BrasCroises_10_Triste.png"
image Chuenpodo BrasCroises Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_11_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Yeuxfermes Rougit = "Chuenpodo/side_BrasCroises_11_Yeuxfermes_Rougit.png"
image Chuenpodo BrasCroises Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_BrasCroises_11_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo BrasCroises Yeuxfermes Rougit = "Chuenpodo/side_BrasCroises_11_Yeuxfermes_Rougit.png"
image Chuenpodo Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_01_Badboy.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Badboy = "Chuenpodo/side_Standard_01_Badboy.png"
image Chuenpodo Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_01_Badboy.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Badboy = "Chuenpodo/side_Standard_01_Badboy.png"
image Chuenpodo Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_02_Badboy_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Badboy Rougit = "Chuenpodo/side_Standard_02_Badboy_Rougit.png"
image Chuenpodo Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_02_Badboy_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Badboy Rougit = "Chuenpodo/side_Standard_02_Badboy_Rougit.png"
image Chuenpodo Standard Colere = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_03_Colere.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Colere = "Chuenpodo/side_Standard_03_Colere.png"
image Chuenpodo Standard Colere = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_03_Colere.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Colere = "Chuenpodo/side_Standard_03_Colere.png"
image Chuenpodo Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_04_Colere_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Colere Rougit = "Chuenpodo/side_Standard_04_Colere_Rougit.png"
image Chuenpodo Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_04_Colere_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Colere Rougit = "Chuenpodo/side_Standard_04_Colere_Rougit.png"
image Chuenpodo Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_05_Degoute.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Degoute = "Chuenpodo/side_Standard_05_Degoute.png"
image Chuenpodo Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_05_Degoute.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Degoute = "Chuenpodo/side_Standard_05_Degoute.png"
image Chuenpodo Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_06_Sourire.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire = "Chuenpodo/side_Standard_06_Sourire.png"
image Chuenpodo Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_06_Sourire.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire = "Chuenpodo/side_Standard_06_Sourire.png"
image Chuenpodo Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_07_Sourire_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire Rougit = "Chuenpodo/side_Standard_07_Sourire_Rougit.png"
image Chuenpodo Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_07_Sourire_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire Rougit = "Chuenpodo/side_Standard_07_Sourire_Rougit.png"
image Chuenpodo Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire Yeuxfermes = "Chuenpodo/side_Standard_08_Sourire_Yeuxfermes.png"
image Chuenpodo Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire Yeuxfermes = "Chuenpodo/side_Standard_08_Sourire_Yeuxfermes.png"
image Chuenpodo Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire Yeuxfermes Rougit = "Chuenpodo/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Chuenpodo Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Sourire Yeuxfermes Rougit = "Chuenpodo/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Chuenpodo Standard Triste = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_10_Triste.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Triste = "Chuenpodo/side_Standard_10_Triste.png"
image Chuenpodo Standard Triste = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_10_Triste.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Triste = "Chuenpodo/side_Standard_10_Triste.png"
image Chuenpodo Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Yeuxfermes Rougit = "Chuenpodo/side_Standard_11_Yeuxfermes_Rougit.png"
image Chuenpodo Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Chuenpodo/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Chuenpodo_low.png")
image side Chuenpodo Standard Yeuxfermes Rougit = "Chuenpodo/side_Standard_11_Yeuxfermes_Rougit.png"
