image Metalice PoseCoucou Cligne = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_01_Cligne.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Cligne = "Metalice/side_PoseCoucou_01_Cligne.png"
image Metalice PoseCoucou Cligne = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_01_Cligne.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Cligne = "Metalice/side_PoseCoucou_01_Cligne.png"
image Metalice PoseCoucou Cligne Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_02_Cligne_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Cligne Rougit = "Metalice/side_PoseCoucou_02_Cligne_Rougit.png"
image Metalice PoseCoucou Cligne Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_02_Cligne_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Cligne Rougit = "Metalice/side_PoseCoucou_02_Cligne_Rougit.png"
image Metalice PoseCoucou Colere = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_03_Colere.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Colere = "Metalice/side_PoseCoucou_03_Colere.png"
image Metalice PoseCoucou Colere = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_03_Colere.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Colere = "Metalice/side_PoseCoucou_03_Colere.png"
image Metalice PoseCoucou Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_04_Colere_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Colere Rougit = "Metalice/side_PoseCoucou_04_Colere_Rougit.png"
image Metalice PoseCoucou Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_04_Colere_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Colere Rougit = "Metalice/side_PoseCoucou_04_Colere_Rougit.png"
image Metalice PoseCoucou Degoute = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_05_Degoute.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Degoute = "Metalice/side_PoseCoucou_05_Degoute.png"
image Metalice PoseCoucou Degoute = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_05_Degoute.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Degoute = "Metalice/side_PoseCoucou_05_Degoute.png"
image Metalice PoseCoucou Sourire = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_06_Sourire.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire = "Metalice/side_PoseCoucou_06_Sourire.png"
image Metalice PoseCoucou Sourire = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_06_Sourire.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire = "Metalice/side_PoseCoucou_06_Sourire.png"
image Metalice PoseCoucou Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_07_Sourire_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire Rougit = "Metalice/side_PoseCoucou_07_Sourire_Rougit.png"
image Metalice PoseCoucou Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_07_Sourire_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire Rougit = "Metalice/side_PoseCoucou_07_Sourire_Rougit.png"
image Metalice PoseCoucou Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_08_Sourire_Yeuxfermes.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire Yeuxfermes = "Metalice/side_PoseCoucou_08_Sourire_Yeuxfermes.png"
image Metalice PoseCoucou Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_08_Sourire_Yeuxfermes.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire Yeuxfermes = "Metalice/side_PoseCoucou_08_Sourire_Yeuxfermes.png"
image Metalice PoseCoucou Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_09_Sourire_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire Yeuxfermes Rougit = "Metalice/side_PoseCoucou_09_Sourire_Yeuxfermes_Rougit.png"
image Metalice PoseCoucou Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_09_Sourire_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Sourire Yeuxfermes Rougit = "Metalice/side_PoseCoucou_09_Sourire_Yeuxfermes_Rougit.png"
image Metalice PoseCoucou Triste = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_10_Triste.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Triste = "Metalice/side_PoseCoucou_10_Triste.png"
image Metalice PoseCoucou Triste = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_10_Triste.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Triste = "Metalice/side_PoseCoucou_10_Triste.png"
image Metalice PoseCoucou Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_11_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Yeuxfermes Rougit = "Metalice/side_PoseCoucou_11_Yeuxfermes_Rougit.png"
image Metalice PoseCoucou Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_PoseCoucou_11_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice PoseCoucou Yeuxfermes Rougit = "Metalice/side_PoseCoucou_11_Yeuxfermes_Rougit.png"
image Metalice Standard Cligne = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_01_Cligne.png", "True", "Metalice_low.png")
image side Metalice Standard Cligne = "Metalice/side_Standard_01_Cligne.png"
image Metalice Standard Cligne = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_01_Cligne.png", "True", "Metalice_low.png")
image side Metalice Standard Cligne = "Metalice/side_Standard_01_Cligne.png"
image Metalice Standard Cligne Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_02_Cligne_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Cligne Rougit = "Metalice/side_Standard_02_Cligne_Rougit.png"
image Metalice Standard Cligne Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_02_Cligne_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Cligne Rougit = "Metalice/side_Standard_02_Cligne_Rougit.png"
image Metalice Standard Colere = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_03_Colere.png", "True", "Metalice_low.png")
image side Metalice Standard Colere = "Metalice/side_Standard_03_Colere.png"
image Metalice Standard Colere = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_03_Colere.png", "True", "Metalice_low.png")
image side Metalice Standard Colere = "Metalice/side_Standard_03_Colere.png"
image Metalice Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_04_Colere_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Colere Rougit = "Metalice/side_Standard_04_Colere_Rougit.png"
image Metalice Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_04_Colere_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Colere Rougit = "Metalice/side_Standard_04_Colere_Rougit.png"
image Metalice Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_05_Degoute.png", "True", "Metalice_low.png")
image side Metalice Standard Degoute = "Metalice/side_Standard_05_Degoute.png"
image Metalice Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_05_Degoute.png", "True", "Metalice_low.png")
image side Metalice Standard Degoute = "Metalice/side_Standard_05_Degoute.png"
image Metalice Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_06_Sourire.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire = "Metalice/side_Standard_06_Sourire.png"
image Metalice Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_06_Sourire.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire = "Metalice/side_Standard_06_Sourire.png"
image Metalice Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_07_Sourire_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire Rougit = "Metalice/side_Standard_07_Sourire_Rougit.png"
image Metalice Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_07_Sourire_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire Rougit = "Metalice/side_Standard_07_Sourire_Rougit.png"
image Metalice Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire Yeuxfermes = "Metalice/side_Standard_08_Sourire_Yeuxfermes.png"
image Metalice Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire Yeuxfermes = "Metalice/side_Standard_08_Sourire_Yeuxfermes.png"
image Metalice Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire Yeuxfermes Rougit = "Metalice/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Metalice Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Sourire Yeuxfermes Rougit = "Metalice/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Metalice Standard Triste = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_10_Triste.png", "True", "Metalice_low.png")
image side Metalice Standard Triste = "Metalice/side_Standard_10_Triste.png"
image Metalice Standard Triste = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_10_Triste.png", "True", "Metalice_low.png")
image side Metalice Standard Triste = "Metalice/side_Standard_10_Triste.png"
image Metalice Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Yeuxfermes Rougit = "Metalice/side_Standard_11_Yeuxfermes_Rougit.png"
image Metalice Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Metalice/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Metalice_low.png")
image side Metalice Standard Yeuxfermes Rougit = "Metalice/side_Standard_11_Yeuxfermes_Rougit.png"
