image Medoc PosePoings Badboy = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_01_Badboy.png", "True", "Medoc_low.png")
image side Medoc PosePoings Badboy = "Medoc/side_PosePoings_01_Badboy.png"
image Medoc PosePoings Badboy = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_01_Badboy.png", "True", "Medoc_low.png")
image side Medoc PosePoings Badboy = "Medoc/side_PosePoings_01_Badboy.png"
image Medoc PosePoings Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_02_Badboy_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Badboy Rougit = "Medoc/side_PosePoings_02_Badboy_Rougit.png"
image Medoc PosePoings Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_02_Badboy_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Badboy Rougit = "Medoc/side_PosePoings_02_Badboy_Rougit.png"
image Medoc PosePoings Colere = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_03_Colere.png", "True", "Medoc_low.png")
image side Medoc PosePoings Colere = "Medoc/side_PosePoings_03_Colere.png"
image Medoc PosePoings Colere = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_03_Colere.png", "True", "Medoc_low.png")
image side Medoc PosePoings Colere = "Medoc/side_PosePoings_03_Colere.png"
image Medoc PosePoings Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_04_Colere_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Colere Rougit = "Medoc/side_PosePoings_04_Colere_Rougit.png"
image Medoc PosePoings Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_04_Colere_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Colere Rougit = "Medoc/side_PosePoings_04_Colere_Rougit.png"
image Medoc PosePoings Degoute = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_05_Degoute.png", "True", "Medoc_low.png")
image side Medoc PosePoings Degoute = "Medoc/side_PosePoings_05_Degoute.png"
image Medoc PosePoings Degoute = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_05_Degoute.png", "True", "Medoc_low.png")
image side Medoc PosePoings Degoute = "Medoc/side_PosePoings_05_Degoute.png"
image Medoc PosePoings Sourire = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_06_Sourire.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire = "Medoc/side_PosePoings_06_Sourire.png"
image Medoc PosePoings Sourire = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_06_Sourire.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire = "Medoc/side_PosePoings_06_Sourire.png"
image Medoc PosePoings Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_07_Sourire_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire Rougit = "Medoc/side_PosePoings_07_Sourire_Rougit.png"
image Medoc PosePoings Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_07_Sourire_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire Rougit = "Medoc/side_PosePoings_07_Sourire_Rougit.png"
image Medoc PosePoings Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_08_Sourire_Yeuxfermes.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire Yeuxfermes = "Medoc/side_PosePoings_08_Sourire_Yeuxfermes.png"
image Medoc PosePoings Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_08_Sourire_Yeuxfermes.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire Yeuxfermes = "Medoc/side_PosePoings_08_Sourire_Yeuxfermes.png"
image Medoc PosePoings Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_09_Sourire_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire Yeuxfermes Rougit = "Medoc/side_PosePoings_09_Sourire_Yeuxfermes_Rougit.png"
image Medoc PosePoings Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_09_Sourire_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Sourire Yeuxfermes Rougit = "Medoc/side_PosePoings_09_Sourire_Yeuxfermes_Rougit.png"
image Medoc PosePoings Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_11_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Yeuxfermes Rougit = "Medoc/side_PosePoings_11_Yeuxfermes_Rougit.png"
image Medoc PosePoings Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_PosePoings_11_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc PosePoings Yeuxfermes Rougit = "Medoc/side_PosePoings_11_Yeuxfermes_Rougit.png"
image Medoc Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_01_Badboy.png", "True", "Medoc_low.png")
image side Medoc Standard Badboy = "Medoc/side_Standard_01_Badboy.png"
image Medoc Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_01_Badboy.png", "True", "Medoc_low.png")
image side Medoc Standard Badboy = "Medoc/side_Standard_01_Badboy.png"
image Medoc Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_02_Badboy_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Badboy Rougit = "Medoc/side_Standard_02_Badboy_Rougit.png"
image Medoc Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_02_Badboy_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Badboy Rougit = "Medoc/side_Standard_02_Badboy_Rougit.png"
image Medoc Standard Colere = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_03_Colere.png", "True", "Medoc_low.png")
image side Medoc Standard Colere = "Medoc/side_Standard_03_Colere.png"
image Medoc Standard Colere = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_03_Colere.png", "True", "Medoc_low.png")
image side Medoc Standard Colere = "Medoc/side_Standard_03_Colere.png"
image Medoc Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_04_Colere_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Colere Rougit = "Medoc/side_Standard_04_Colere_Rougit.png"
image Medoc Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_04_Colere_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Colere Rougit = "Medoc/side_Standard_04_Colere_Rougit.png"
image Medoc Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_05_Degoute.png", "True", "Medoc_low.png")
image side Medoc Standard Degoute = "Medoc/side_Standard_05_Degoute.png"
image Medoc Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_05_Degoute.png", "True", "Medoc_low.png")
image side Medoc Standard Degoute = "Medoc/side_Standard_05_Degoute.png"
image Medoc Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_06_Sourire.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire = "Medoc/side_Standard_06_Sourire.png"
image Medoc Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_06_Sourire.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire = "Medoc/side_Standard_06_Sourire.png"
image Medoc Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_07_Sourire_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire Rougit = "Medoc/side_Standard_07_Sourire_Rougit.png"
image Medoc Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_07_Sourire_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire Rougit = "Medoc/side_Standard_07_Sourire_Rougit.png"
image Medoc Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire Yeuxfermes = "Medoc/side_Standard_08_Sourire_Yeuxfermes.png"
image Medoc Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire Yeuxfermes = "Medoc/side_Standard_08_Sourire_Yeuxfermes.png"
image Medoc Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire Yeuxfermes Rougit = "Medoc/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Medoc Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Sourire Yeuxfermes Rougit = "Medoc/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Medoc Standard Triste = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_10_Triste.png", "True", "Medoc_low.png")
image side Medoc Standard Triste = "Medoc/side_Standard_10_Triste.png"
image Medoc Standard Triste = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_10_Triste.png", "True", "Medoc_low.png")
image side Medoc Standard Triste = "Medoc/side_Standard_10_Triste.png"
image Medoc Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Yeuxfermes Rougit = "Medoc/side_Standard_11_Yeuxfermes_Rougit.png"
image Medoc Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Standard Yeuxfermes Rougit = "Medoc/side_Standard_11_Yeuxfermes_Rougit.png"
image Medoc Topless Badboy = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_01_Badboy.png", "True", "Medoc_low.png")
image side Medoc Topless Badboy = "Medoc/side_Topless_01_Badboy.png"
image Medoc Topless Badboy = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_01_Badboy.png", "True", "Medoc_low.png")
image side Medoc Topless Badboy = "Medoc/side_Topless_01_Badboy.png"
image Medoc Topless Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_02_Badboy_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Badboy Rougit = "Medoc/side_Topless_02_Badboy_Rougit.png"
image Medoc Topless Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_02_Badboy_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Badboy Rougit = "Medoc/side_Topless_02_Badboy_Rougit.png"
image Medoc Topless Colere = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_03_Colere.png", "True", "Medoc_low.png")
image side Medoc Topless Colere = "Medoc/side_Topless_03_Colere.png"
image Medoc Topless Colere = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_03_Colere.png", "True", "Medoc_low.png")
image side Medoc Topless Colere = "Medoc/side_Topless_03_Colere.png"
image Medoc Topless Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_04_Colere_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Colere Rougit = "Medoc/side_Topless_04_Colere_Rougit.png"
image Medoc Topless Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_04_Colere_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Colere Rougit = "Medoc/side_Topless_04_Colere_Rougit.png"
image Medoc Topless Degoute = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_05_Degoute.png", "True", "Medoc_low.png")
image side Medoc Topless Degoute = "Medoc/side_Topless_05_Degoute.png"
image Medoc Topless Degoute = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_05_Degoute.png", "True", "Medoc_low.png")
image side Medoc Topless Degoute = "Medoc/side_Topless_05_Degoute.png"
image Medoc Topless Sourire = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_06_Sourire.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire = "Medoc/side_Topless_06_Sourire.png"
image Medoc Topless Sourire = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_06_Sourire.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire = "Medoc/side_Topless_06_Sourire.png"
image Medoc Topless Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_07_Sourire_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire Rougit = "Medoc/side_Topless_07_Sourire_Rougit.png"
image Medoc Topless Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_07_Sourire_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire Rougit = "Medoc/side_Topless_07_Sourire_Rougit.png"
image Medoc Topless Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_08_Sourire_Yeuxfermes.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire Yeuxfermes = "Medoc/side_Topless_08_Sourire_Yeuxfermes.png"
image Medoc Topless Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_08_Sourire_Yeuxfermes.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire Yeuxfermes = "Medoc/side_Topless_08_Sourire_Yeuxfermes.png"
image Medoc Topless Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_09_Sourire_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire Yeuxfermes Rougit = "Medoc/side_Topless_09_Sourire_Yeuxfermes_Rougit.png"
image Medoc Topless Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_09_Sourire_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Sourire Yeuxfermes Rougit = "Medoc/side_Topless_09_Sourire_Yeuxfermes_Rougit.png"
image Medoc Topless Triste = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_10_Triste.png", "True", "Medoc_low.png")
image side Medoc Topless Triste = "Medoc/side_Topless_10_Triste.png"
image Medoc Topless Triste = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_10_Triste.png", "True", "Medoc_low.png")
image side Medoc Topless Triste = "Medoc/side_Topless_10_Triste.png"
image Medoc Topless Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_11_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Yeuxfermes Rougit = "Medoc/side_Topless_11_Yeuxfermes_Rougit.png"
image Medoc Topless Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Medoc/main_Topless_11_Yeuxfermes_Rougit.png", "True", "Medoc_low.png")
image side Medoc Topless Yeuxfermes Rougit = "Medoc/side_Topless_11_Yeuxfermes_Rougit.png"
