image Mickey Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_01_Badboy.png", "True", "Mickey_low.png")
image side Mickey Standard Badboy = "Mickey/side_Standard_01_Badboy.png"
image Mickey Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_01_Badboy.png", "True", "Mickey_low.png")
image side Mickey Standard Badboy = "Mickey/side_Standard_01_Badboy.png"
image Mickey Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_02_Badboy_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Badboy Rougit = "Mickey/side_Standard_02_Badboy_Rougit.png"
image Mickey Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_02_Badboy_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Badboy Rougit = "Mickey/side_Standard_02_Badboy_Rougit.png"
image Mickey Standard Colere = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_03_Colere.png", "True", "Mickey_low.png")
image side Mickey Standard Colere = "Mickey/side_Standard_03_Colere.png"
image Mickey Standard Colere = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_03_Colere.png", "True", "Mickey_low.png")
image side Mickey Standard Colere = "Mickey/side_Standard_03_Colere.png"
image Mickey Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_04_Colere_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Colere Rougit = "Mickey/side_Standard_04_Colere_Rougit.png"
image Mickey Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_04_Colere_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Colere Rougit = "Mickey/side_Standard_04_Colere_Rougit.png"
image Mickey Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_05_Degoute.png", "True", "Mickey_low.png")
image side Mickey Standard Degoute = "Mickey/side_Standard_05_Degoute.png"
image Mickey Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_05_Degoute.png", "True", "Mickey_low.png")
image side Mickey Standard Degoute = "Mickey/side_Standard_05_Degoute.png"
image Mickey Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_06_Sourire.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire = "Mickey/side_Standard_06_Sourire.png"
image Mickey Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_06_Sourire.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire = "Mickey/side_Standard_06_Sourire.png"
image Mickey Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_07_Sourire_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire Rougit = "Mickey/side_Standard_07_Sourire_Rougit.png"
image Mickey Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_07_Sourire_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire Rougit = "Mickey/side_Standard_07_Sourire_Rougit.png"
image Mickey Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire Yeuxfermes = "Mickey/side_Standard_08_Sourire_Yeuxfermes.png"
image Mickey Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire Yeuxfermes = "Mickey/side_Standard_08_Sourire_Yeuxfermes.png"
image Mickey Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire Yeuxfermes Rougit = "Mickey/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Mickey Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Sourire Yeuxfermes Rougit = "Mickey/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Mickey Standard Triste = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_10_Triste.png", "True", "Mickey_low.png")
image side Mickey Standard Triste = "Mickey/side_Standard_10_Triste.png"
image Mickey Standard Triste = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_10_Triste.png", "True", "Mickey_low.png")
image side Mickey Standard Triste = "Mickey/side_Standard_10_Triste.png"
image Mickey Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Yeuxfermes Rougit = "Mickey/side_Standard_11_Yeuxfermes_Rougit.png"
image Mickey Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Mickey/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Mickey_low.png")
image side Mickey Standard Yeuxfermes Rougit = "Mickey/side_Standard_11_Yeuxfermes_Rougit.png"
