image Von BrasCroises Badboy = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_01_Badboy.png", "True", "Von_low.png")
image side Von BrasCroises Badboy = "Von/side_BrasCroises_01_Badboy.png"
image Von BrasCroises Badboy = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_01_Badboy.png", "True", "Von_low.png")
image side Von BrasCroises Badboy = "Von/side_BrasCroises_01_Badboy.png"
image Von BrasCroises Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_02_Badboy_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Badboy Rougit = "Von/side_BrasCroises_02_Badboy_Rougit.png"
image Von BrasCroises Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_02_Badboy_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Badboy Rougit = "Von/side_BrasCroises_02_Badboy_Rougit.png"
image Von BrasCroises Colere = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_03_Colere.png", "True", "Von_low.png")
image side Von BrasCroises Colere = "Von/side_BrasCroises_03_Colere.png"
image Von BrasCroises Colere = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_03_Colere.png", "True", "Von_low.png")
image side Von BrasCroises Colere = "Von/side_BrasCroises_03_Colere.png"
image Von BrasCroises Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_04_Colere_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Colere Rougit = "Von/side_BrasCroises_04_Colere_Rougit.png"
image Von BrasCroises Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_04_Colere_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Colere Rougit = "Von/side_BrasCroises_04_Colere_Rougit.png"
image Von BrasCroises Degoute = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_05_Degoute.png", "True", "Von_low.png")
image side Von BrasCroises Degoute = "Von/side_BrasCroises_05_Degoute.png"
image Von BrasCroises Degoute = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_05_Degoute.png", "True", "Von_low.png")
image side Von BrasCroises Degoute = "Von/side_BrasCroises_05_Degoute.png"
image Von BrasCroises Sourire = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_06_Sourire.png", "True", "Von_low.png")
image side Von BrasCroises Sourire = "Von/side_BrasCroises_06_Sourire.png"
image Von BrasCroises Sourire = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_06_Sourire.png", "True", "Von_low.png")
image side Von BrasCroises Sourire = "Von/side_BrasCroises_06_Sourire.png"
image Von BrasCroises Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_07_Sourire_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Sourire Rougit = "Von/side_BrasCroises_07_Sourire_Rougit.png"
image Von BrasCroises Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_07_Sourire_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Sourire Rougit = "Von/side_BrasCroises_07_Sourire_Rougit.png"
image Von BrasCroises Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_08_Sourire_Yeuxfermes.png", "True", "Von_low.png")
image side Von BrasCroises Sourire Yeuxfermes = "Von/side_BrasCroises_08_Sourire_Yeuxfermes.png"
image Von BrasCroises Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_08_Sourire_Yeuxfermes.png", "True", "Von_low.png")
image side Von BrasCroises Sourire Yeuxfermes = "Von/side_BrasCroises_08_Sourire_Yeuxfermes.png"
image Von BrasCroises Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Sourire Yeuxfermes Rougit = "Von/side_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png"
image Von BrasCroises Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Sourire Yeuxfermes Rougit = "Von/side_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png"
image Von BrasCroises Triste = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_10_Triste.png", "True", "Von_low.png")
image side Von BrasCroises Triste = "Von/side_BrasCroises_10_Triste.png"
image Von BrasCroises Triste = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_10_Triste.png", "True", "Von_low.png")
image side Von BrasCroises Triste = "Von/side_BrasCroises_10_Triste.png"
image Von BrasCroises Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_11_Yeuxfermes_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Yeuxfermes Rougit = "Von/side_BrasCroises_11_Yeuxfermes_Rougit.png"
image Von BrasCroises Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Von/main_BrasCroises_11_Yeuxfermes_Rougit.png", "True", "Von_low.png")
image side Von BrasCroises Yeuxfermes Rougit = "Von/side_BrasCroises_11_Yeuxfermes_Rougit.png"
