image Foulk Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_01_Badboy.png", "True", "Foulk_low.png")
image side Foulk Standard Badboy = "Foulk/side_Standard_01_Badboy.png"
image Foulk Standard Badboy = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_01_Badboy.png", "True", "Foulk_low.png")
image side Foulk Standard Badboy = "Foulk/side_Standard_01_Badboy.png"
image Foulk Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_02_Badboy_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Badboy Rougit = "Foulk/side_Standard_02_Badboy_Rougit.png"
image Foulk Standard Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_02_Badboy_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Badboy Rougit = "Foulk/side_Standard_02_Badboy_Rougit.png"
image Foulk Standard Colere = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_03_Colere.png", "True", "Foulk_low.png")
image side Foulk Standard Colere = "Foulk/side_Standard_03_Colere.png"
image Foulk Standard Colere = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_03_Colere.png", "True", "Foulk_low.png")
image side Foulk Standard Colere = "Foulk/side_Standard_03_Colere.png"
image Foulk Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_04_Colere_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Colere Rougit = "Foulk/side_Standard_04_Colere_Rougit.png"
image Foulk Standard Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_04_Colere_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Colere Rougit = "Foulk/side_Standard_04_Colere_Rougit.png"
image Foulk Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_05_Degoute.png", "True", "Foulk_low.png")
image side Foulk Standard Degoute = "Foulk/side_Standard_05_Degoute.png"
image Foulk Standard Degoute = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_05_Degoute.png", "True", "Foulk_low.png")
image side Foulk Standard Degoute = "Foulk/side_Standard_05_Degoute.png"
image Foulk Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_06_Sourire.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire = "Foulk/side_Standard_06_Sourire.png"
image Foulk Standard Sourire = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_06_Sourire.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire = "Foulk/side_Standard_06_Sourire.png"
image Foulk Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_07_Sourire_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire Rougit = "Foulk/side_Standard_07_Sourire_Rougit.png"
image Foulk Standard Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_07_Sourire_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire Rougit = "Foulk/side_Standard_07_Sourire_Rougit.png"
image Foulk Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire Yeuxfermes = "Foulk/side_Standard_08_Sourire_Yeuxfermes.png"
image Foulk Standard Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_08_Sourire_Yeuxfermes.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire Yeuxfermes = "Foulk/side_Standard_08_Sourire_Yeuxfermes.png"
image Foulk Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire Yeuxfermes Rougit = "Foulk/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Foulk Standard Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_09_Sourire_Yeuxfermes_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Sourire Yeuxfermes Rougit = "Foulk/side_Standard_09_Sourire_Yeuxfermes_Rougit.png"
image Foulk Standard Triste = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_10_Triste.png", "True", "Foulk_low.png")
image side Foulk Standard Triste = "Foulk/side_Standard_10_Triste.png"
image Foulk Standard Triste = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_10_Triste.png", "True", "Foulk_low.png")
image side Foulk Standard Triste = "Foulk/side_Standard_10_Triste.png"
image Foulk Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Yeuxfermes Rougit = "Foulk/side_Standard_11_Yeuxfermes_Rougit.png"
image Foulk Standard Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Foulk/main_Standard_11_Yeuxfermes_Rougit.png", "True", "Foulk_low.png")
image side Foulk Standard Yeuxfermes Rougit = "Foulk/side_Standard_11_Yeuxfermes_Rougit.png"
