image Dieuvomi BrasCroises Badboy = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_01_Badboy.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Badboy = "Dieuvomi/side_BrasCroises_01_Badboy.png"
image Dieuvomi BrasCroises Badboy = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_01_Badboy.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Badboy = "Dieuvomi/side_BrasCroises_01_Badboy.png"
image Dieuvomi BrasCroises Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_02_Badboy_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Badboy Rougit = "Dieuvomi/side_BrasCroises_02_Badboy_Rougit.png"
image Dieuvomi BrasCroises Badboy Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_02_Badboy_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Badboy Rougit = "Dieuvomi/side_BrasCroises_02_Badboy_Rougit.png"
image Dieuvomi BrasCroises Colere = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_03_Colere.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Colere = "Dieuvomi/side_BrasCroises_03_Colere.png"
image Dieuvomi BrasCroises Colere = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_03_Colere.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Colere = "Dieuvomi/side_BrasCroises_03_Colere.png"
image Dieuvomi BrasCroises Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_04_Colere_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Colere Rougit = "Dieuvomi/side_BrasCroises_04_Colere_Rougit.png"
image Dieuvomi BrasCroises Colere Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_04_Colere_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Colere Rougit = "Dieuvomi/side_BrasCroises_04_Colere_Rougit.png"
image Dieuvomi BrasCroises Degoute = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_05_Degoute.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Degoute = "Dieuvomi/side_BrasCroises_05_Degoute.png"
image Dieuvomi BrasCroises Degoute = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_05_Degoute.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Degoute = "Dieuvomi/side_BrasCroises_05_Degoute.png"
image Dieuvomi BrasCroises Sourire = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_06_Sourire.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire = "Dieuvomi/side_BrasCroises_06_Sourire.png"
image Dieuvomi BrasCroises Sourire = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_06_Sourire.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire = "Dieuvomi/side_BrasCroises_06_Sourire.png"
image Dieuvomi BrasCroises Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_07_Sourire_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire Rougit = "Dieuvomi/side_BrasCroises_07_Sourire_Rougit.png"
image Dieuvomi BrasCroises Sourire Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_07_Sourire_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire Rougit = "Dieuvomi/side_BrasCroises_07_Sourire_Rougit.png"
image Dieuvomi BrasCroises Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_08_Sourire_Yeuxfermes.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire Yeuxfermes = "Dieuvomi/side_BrasCroises_08_Sourire_Yeuxfermes.png"
image Dieuvomi BrasCroises Sourire Yeuxfermes = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_08_Sourire_Yeuxfermes.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire Yeuxfermes = "Dieuvomi/side_BrasCroises_08_Sourire_Yeuxfermes.png"
image Dieuvomi BrasCroises Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire Yeuxfermes Rougit = "Dieuvomi/side_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png"
image Dieuvomi BrasCroises Sourire Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Sourire Yeuxfermes Rougit = "Dieuvomi/side_BrasCroises_09_Sourire_Yeuxfermes_Rougit.png"
image Dieuvomi BrasCroises Triste = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_10_Triste.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Triste = "Dieuvomi/side_BrasCroises_10_Triste.png"
image Dieuvomi BrasCroises Triste = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_10_Triste.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Triste = "Dieuvomi/side_BrasCroises_10_Triste.png"
image Dieuvomi BrasCroises Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_11_Yeuxfermes_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Yeuxfermes Rougit = "Dieuvomi/side_BrasCroises_11_Yeuxfermes_Rougit.png"
image Dieuvomi BrasCroises Yeuxfermes Rougit = ConditionSwitch("persistent.ultra_quality", "Dieuvomi/main_BrasCroises_11_Yeuxfermes_Rougit.png", "True", "Dieuvomi_low.png")
image side Dieuvomi BrasCroises Yeuxfermes Rougit = "Dieuvomi/side_BrasCroises_11_Yeuxfermes_Rougit.png"
